# Generated by Django 5.0.6 on 2024-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
