# Generated by Django 5.0.6 on 2024-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
