# Generated by Django 5.0.6 on 2024-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_currentbid_comments_listing_alter_bids_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
