# Generated by Django 5.0.6 on 2024-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='currentBid',
            new_name='listing',
        ),
    ]
