# Generated by Django 5.0.6 on 2024-07-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_onwatch_listings_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='onwatch',
        ),
    ]
