# Generated by Django 5.0.6 on 2024-07-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listings_onwatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='winner',
        ),
    ]
