# Generated by Django 5.0.6 on 2024-07-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listings_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='onwatch',
        ),
    ]
