# Generated by Django 5.0.6 on 2024-07-17 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listings_onwatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='onwatch',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
